{
 "title": "FOSSA Executive Product Summary",
 "tags": [ "Author:Tanmay" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "product_name",
    "label": "PRODUCT",
    "query": "SELECT distinct product from product_repo_map;"
   }
  ]
 },
 "panels": [
  { "title": "Security Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select count(*) as COUNT from VULNERABILITY where issue_type = \"Security Issue\" and project in (\r\nselect project from product_repo_map where product = \"$product_name\");\r\n\r\n",
     "rawQueryText": "select count(*) as COUNT from VULNERABILITY where issue_type = \"Security Issue\" and project in (\r\nselect project from product_repo_map where product = \"$product_name\");\r\n\r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Vulnerability",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 1 },
   "targets": [
    {
     "queryText": "select cvss_severity as SEVERITY, count(*) as COUNT from VULNERABILITY where  project in (\r\nselect project from product_repo_map where product = \"$product_name\") and issue_type=\"Security Issue\" group by cvss_severity;",
     "rawQueryText": "select cvss_severity as SEVERITY, count(*) as COUNT from VULNERABILITY where  project in (\r\nselect project from product_repo_map where product = \"$product_name\") and issue_type=\"Security Issue\" group by cvss_severity;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Category",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 1 },
   "targets": [
    {
     "queryText": "select issue_type as \"ISSUE TYPE\", count(*) as COUNT from VULNERABILITY where  project in (\r\nselect project from product_repo_map where product = \"$product_name\") group by issue_type;",
     "rawQueryText": "select issue_type as \"ISSUE TYPE\", count(*) as COUNT from VULNERABILITY where  project in (\r\nselect project from product_repo_map where product = \"$product_name\") group by issue_type;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Modules",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "queryText": "select project from product_repo_map where product = \"$product_name\"",
     "rawQueryText": "select project from product_repo_map where product = \"$product_name\"",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Vulnerability Graph",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "select scan_date, count(*) from VULNERABILITY_HIST where issue_type= \"Security Issue\" and project in (\r\nselect project from product_repo_map where product = \"$product_name\") group by scan_date;",
     "rawQueryText": "select scan_date, count(*) from VULNERABILITY_HIST where issue_type= \"Security Issue\" and project in (\r\nselect project from product_repo_map where product = \"$product_name\") group by scan_date;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Sonar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Quality Gate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "select case when STATUS = 0 then \"OK\" when STATUS > 0 then \"ERROR\" END as STATUS from (\r\n\r\nselect SUM (case \r\nwhen quality_gate_status = \"OK\" then 0\r\nwhen quality_gate_status = \"ERROR\" then 1 END) as \"STATUS\"\r\n from sonar_metrics where project in (\r\nselect project from product_repo_map where product = \"$product_name\")\r\n)",
     "rawQueryText": "select case when STATUS = 0 then \"OK\" when STATUS > 0 then \"ERROR\" END as STATUS from (\r\n\r\nselect SUM (case \r\nwhen quality_gate_status = \"OK\" then 0\r\nwhen quality_gate_status = \"ERROR\" then 1 END) as \"STATUS\"\r\n from sonar_metrics where project in (\r\nselect project from product_repo_map where product = \"$product_name\")\r\n)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Overall Metrics",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 17 },
   "targets": [
    {
     "queryText": "select 'overall_code_smells' As \"Metric\" , overall_code_smells as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'overall_coverage'  As \"Metric\" , overall_coverage as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'overall_security_hotspots_reviewed' As \"Metric\" , overall_security_hotspots_reviewed as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'overall_bugs'  As \"Metric\" , overall_bugs as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'overall_duplicated_lines_density' As \"Metric\" , overall_duplicated_lines_density as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'overall_vulnerabilities'  As \"Metric\" , overall_vulnerabilities as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric",
     "rawQueryText": "select 'overall_code_smells' As \"Metric\" , overall_code_smells as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'overall_coverage'  As \"Metric\" , overall_coverage as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'overall_security_hotspots_reviewed' As \"Metric\" , overall_security_hotspots_reviewed as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'overall_bugs'  As \"Metric\" , overall_bugs as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'overall_duplicated_lines_density' As \"Metric\" , overall_duplicated_lines_density as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'overall_vulnerabilities'  As \"Metric\" , overall_vulnerabilities as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "New Code Metrics",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 17 },
   "targets": [
    {
     "queryText": "select 'new_code_smells' As \"Metric\" , new_code_smells as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'new_coverage'  As \"Metric\" , new_coverage as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'new_security_hotspots_reviewed' As \"Metric\" , new_security_hotspots_reviewed as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'new_bugs'  As \"Metric\" , new_bugs as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'new_vulnerabilities' As \"Metric\" , new_vulnerabilities as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'new_duplicated_lines_density'  As \"Metric\" , new_duplicated_lines_density as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric",
     "rawQueryText": "select 'new_code_smells' As \"Metric\" , new_code_smells as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'new_coverage'  As \"Metric\" , new_coverage as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'new_security_hotspots_reviewed' As \"Metric\" , new_security_hotspots_reviewed as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'new_bugs'  As \"Metric\" , new_bugs as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'new_vulnerabilities' As \"Metric\" , new_vulnerabilities as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric\nUNION\nselect 'new_duplicated_lines_density'  As \"Metric\" , new_duplicated_lines_density as \"Metric Value\" from sonar_metrics where project in (\nselect project from product_repo_map where product = \"$product_name\") group by Metric",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}