{
 "title": "FOSSA Developer Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_name",
    "label": "PROJECT",
    "query": "SELECT product_name from PRODUCTS;"
   }
  ]
 },
 "panels": [
  {
   "title": "Security Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "select count(*) as COUNT from VULNERABILITY where issue_type = \"Security Issue\" and project=\"$project_name\";\r\n\r\n",
       "rawQueryText": "select count(*) as COUNT from VULNERABILITY where issue_type = \"Security Issue\" and project=\"$project_name\";\r\n\r\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Vulnerability",
     "type": "table",
     "gridPos": { "h": 6, "w": 7, "x": 4, "y": 1 },
     "targets": [
      {
       "queryText": "select cvss_severity as SEVERITY, count(*) as COUNT from VULNERABILITY where  project=\"$project_name\" and issue_type=\"Security Issue\" group by cvss_severity;",
       "rawQueryText": "select cvss_severity as SEVERITY, count(*) as COUNT from VULNERABILITY where  project=\"$project_name\" and issue_type=\"Security Issue\" group by cvss_severity;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Category",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 11, "y": 1 },
     "targets": [
      {
       "queryText": "select issue_type as \"ISSUE TYPE\", count(*) as COUNT from VULNERABILITY where  project=\"$project_name\" group by issue_type;",
       "rawQueryText": "select issue_type as \"ISSUE TYPE\", count(*) as COUNT from VULNERABILITY where  project=\"$project_name\" group by issue_type;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Fix Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
     "targets": [
      {
       "queryText": "select a.cvss_severity as SEVERITY, FIXABLE, NO_FIX , (FIXABLE+ NO_FIX) as TOTAL from (\nselect cvss_severity , count(*) as NO_FIX from VULNERABILITY WHERE  project=\"$project_name\" and  fix_version=\"NO_SAFE_VERSION\" group by cvss_severity\n) a,\n(select cvss_severity, count(*) as FIXABLE from VULNERABILITY WHERE  project=\"$project_name\" and  fix_version!=\"NO_SAFE_VERSION\" group by cvss_severity\n\n) b where a.cvss_severity=b.cvss_severity group by SEVERITY;\n",
       "rawQueryText": "select a.cvss_severity as SEVERITY, FIXABLE, NO_FIX , (FIXABLE+ NO_FIX) as TOTAL from (\nselect cvss_severity , count(*) as NO_FIX from VULNERABILITY WHERE  project=\"$project_name\" and  fix_version=\"NO_SAFE_VERSION\" group by cvss_severity\n) a,\n(select cvss_severity, count(*) as FIXABLE from VULNERABILITY WHERE  project=\"$project_name\" and  fix_version!=\"NO_SAFE_VERSION\" group by cvss_severity\n\n) b where a.cvss_severity=b.cvss_severity group by SEVERITY;\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Fix Available",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 7 },
     "targets": [
      {
       "queryText": "select distinct dependency, current_version, fix_version from VULNERABILITY where  project=\"$project_name\" and issue_type=\"Security Issue\" and fix_version!=\"NO_SAFE_VERSION\";",
       "rawQueryText": "select distinct dependency, current_version, fix_version from VULNERABILITY where  project=\"$project_name\" and issue_type=\"Security Issue\" and fix_version!=\"NO_SAFE_VERSION\";",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  { "title": "Sonar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Overall Metrics",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "queryText": "select overall_code_smells,overall_coverage,overall_security_hotspots_reviewed,overall_bugs,overall_vulnerabilities,overall_duplicated_lines_density from sonar_metrics where project = \"$project_name\"",
     "rawQueryText": "select overall_code_smells,overall_coverage,overall_security_hotspots_reviewed,overall_bugs,overall_vulnerabilities,overall_duplicated_lines_density from sonar_metrics where project = \"$project_name\"",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "New Code",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "queryText": "select new_code_smells,new_coverage,new_security_hotspots_reviewed,new_bugs,new_vulnerabilities,new_duplicated_lines_density from sonar_metrics where project = \"$project_name\"\n",
     "rawQueryText": "select new_code_smells,new_coverage,new_security_hotspots_reviewed,new_bugs,new_vulnerabilities,new_duplicated_lines_density from sonar_metrics where project = \"$project_name\"\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Tech Stack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Java Stack",
     "type": "table",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 26 },
     "targets": [
      {
       "queryText": "select java_version as JAVA, spring_version as SPRING, spring_boot_version as SPRINGBOOT from project_java_stack where project =  \"$project_name\";",
       "rawQueryText": "select java_version as JAVA, spring_version as SPRING, spring_boot_version as SPRINGBOOT from project_java_stack where project =  \"$project_name\";",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "AWS Services",
     "type": "stat",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "queryText": "select aws_services AS \" \" from project_aws_stack where project = \"$project_name\"",
       "rawQueryText": "select aws_services AS \" \" from project_aws_stack where project = \"$project_name\"",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "TECHNOLOGIES",
     "type": "stat",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "queryText": "SELECT other_tech as \" \" from project_tech_stack where project =  \"$project_name\";",
       "rawQueryText": "SELECT other_tech as \" \" from project_tech_stack where project =  \"$project_name\";",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  }
 ]
}