{
 "title": "FOSSA Executive Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_name",
    "label": "PROJECT",
    "query": "SELECT product_name from PRODUCTS;"
   }
  ]
 },
 "panels": [
  { "title": "Security Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select count(*) as COUNT from VULNERABILITY where issue_type = \"Security Issue\" and project=\"$project_name\";\r\n\r\n",
     "rawQueryText": "select count(*) as COUNT from VULNERABILITY where issue_type = \"Security Issue\" and project=\"$project_name\";\r\n\r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Vulnerability",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "queryText": "select cvss_severity as SEVERITY, count(*) as COUNT from VULNERABILITY where  project=\"$project_name\" and issue_type=\"Security Issue\" group by cvss_severity;",
     "rawQueryText": "select cvss_severity as SEVERITY, count(*) as COUNT from VULNERABILITY where  project=\"$project_name\" and issue_type=\"Security Issue\" group by cvss_severity;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Category",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 1 },
   "targets": [
    {
     "queryText": "select issue_type as \"ISSUE TYPE\", count(*) as COUNT from VULNERABILITY where  project=\"$project_name\" group by issue_type;",
     "rawQueryText": "select issue_type as \"ISSUE TYPE\", count(*) as COUNT from VULNERABILITY where  project=\"$project_name\" group by issue_type;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Vulnerability Graph",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "select scan_date, count(*) from VULNERABILITY_HIST where issue_type= \"Security Issue\" and  project=\"$project_name\" group by scan_date;",
     "rawQueryText": "select scan_date, count(*) from VULNERABILITY_HIST where issue_type= \"Security Issue\" and  project=\"$project_name\" group by scan_date;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Tech Stack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Java Stack",
   "type": "table",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "queryText": "select java_version as JAVA, spring_version as SPRING, spring_boot_version as SPRINGBOOT from project_java_stack where project =  \"$project_name\";",
     "rawQueryText": "select java_version as JAVA, spring_version as SPRING, spring_boot_version as SPRINGBOOT from project_java_stack where project =  \"$project_name\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "AWS Services",
   "type": "stat",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "select aws_services AS \" \" from project_aws_stack where project = \"$project_name\"",
     "rawQueryText": "select aws_services AS \" \" from project_aws_stack where project = \"$project_name\"",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "TECHNOLOGIES",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT other_tech as \" \" from project_tech_stack where project =  \"$project_name\";",
     "rawQueryText": "SELECT other_tech as \" \" from project_tech_stack where project =  \"$project_name\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}