{
 "title": "FOSSA Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_name",
    "label": "PROJECT",
    "query": "SELECT product_name from PRODUCTS;"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select count(*) as COUNT from VULNERABILITY where issue_type = \"Security Issue\" and project=\"$project_name\";\r\n\r\n",
     "rawQueryText": "select count(*) as COUNT from VULNERABILITY where issue_type = \"Security Issue\" and project=\"$project_name\";\r\n\r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Vulnerability",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 1 },
   "targets": [
    {
     "queryText": "select cvss_severity as SEVERITY, count(*) as COUNT from VULNERABILITY where  project=\"$project_name\" and issue_type=\"Security Issue\" group by cvss_severity;",
     "rawQueryText": "select cvss_severity as SEVERITY, count(*) as COUNT from VULNERABILITY where  project=\"$project_name\" and issue_type=\"Security Issue\" group by cvss_severity;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Vulnerability Graph",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "select scan_date, count(*) from VULNERABILITY_HIST where issue_type= \"Security Issue\" and  project=\"$project_name\" group by scan_date;",
     "rawQueryText": "select scan_date, count(*) from VULNERABILITY_HIST where issue_type= \"Security Issue\" and  project=\"$project_name\" group by scan_date;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Fix Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "queryText": "select a.cvss_severity as SEVERITY, FIXABLE, NO_FIX , (FIXABLE+ NO_FIX) as TOTAL from (\nselect cvss_severity , count(*) as NO_FIX from VULNERABILITY WHERE  project=\"$project_name\" and  fix_version=\"NO_SAFE_VERSION\" group by cvss_severity\n) a,\n(select cvss_severity, count(*) as FIXABLE from VULNERABILITY WHERE  project=\"$project_name\" and  fix_version!=\"NO_SAFE_VERSION\" group by cvss_severity\n\n) b where a.cvss_severity=b.cvss_severity group by SEVERITY;\n",
     "rawQueryText": "select a.cvss_severity as SEVERITY, FIXABLE, NO_FIX , (FIXABLE+ NO_FIX) as TOTAL from (\nselect cvss_severity , count(*) as NO_FIX from VULNERABILITY WHERE  project=\"$project_name\" and  fix_version=\"NO_SAFE_VERSION\" group by cvss_severity\n) a,\n(select cvss_severity, count(*) as FIXABLE from VULNERABILITY WHERE  project=\"$project_name\" and  fix_version!=\"NO_SAFE_VERSION\" group by cvss_severity\n\n) b where a.cvss_severity=b.cvss_severity group by SEVERITY;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Category",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 9 },
   "targets": [
    {
     "queryText": "select issue_type as \"ISSUE TYPE\", count(*) as COUNT from VULNERABILITY where  project=\"$project_name\" group by issue_type;",
     "rawQueryText": "select issue_type as \"ISSUE TYPE\", count(*) as COUNT from VULNERABILITY where  project=\"$project_name\" group by issue_type;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Fix Available",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
   "targets": [
    {
     "queryText": "select distinct dependency, current_version, fix_version from VULNERABILITY where  project=\"$project_name\" and issue_type=\"Security Issue\" and fix_version!=\"NO_SAFE_VERSION\";",
     "rawQueryText": "select distinct dependency, current_version, fix_version from VULNERABILITY where  project=\"$project_name\" and issue_type=\"Security Issue\" and fix_version!=\"NO_SAFE_VERSION\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}