{
 "title": "SECURITY OVERVIEW",
 "description": "This Dashboard gives an Security Overview of all the products. You can see the count of Security, Quality and License Issues for the product by hovering. Also you can see the details in Executive Dashboard using the link.",
 "tags": [ "Author:Tanmay" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "FOSSA Status",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "select z.product_name as PRODUCT, COALESCE(a.SECURITY_ISSUE,0) as SECURITY,COALESCE(b.QUALITY_ISSUE,0) as QUALITY,COALESCE(c.LICENSE_ISSUE,0) as LICENSE from PRODUCTS z left join\n(select project, count(*) as SECURITY_ISSUE from VULNERABILITY where  issue_type=\"Security Issue\" group by project) a\non z.product_name=a.project \nleft join\n(select project, count(*) as QUALITY_ISSUE from VULNERABILITY where  issue_type=\"outdated dependency\" group by project) b\non z.product_name=b.project\nleft join \n(select project, count(*) as LICENSE_ISSUE from VULNERABILITY where  issue_type=\"unlicensed dependency\" group by project) c\non z.product_name=c.project \ngroup by z.product_name;",
     "rawQueryText": "select z.product_name as PRODUCT, COALESCE(a.SECURITY_ISSUE,0) as SECURITY,COALESCE(b.QUALITY_ISSUE,0) as QUALITY,COALESCE(c.LICENSE_ISSUE,0) as LICENSE from PRODUCTS z left join\n(select project, count(*) as SECURITY_ISSUE from VULNERABILITY where  issue_type=\"Security Issue\" group by project) a\non z.product_name=a.project \nleft join\n(select project, count(*) as QUALITY_ISSUE from VULNERABILITY where  issue_type=\"outdated dependency\" group by project) b\non z.product_name=b.project\nleft join \n(select project, count(*) as LICENSE_ISSUE from VULNERABILITY where  issue_type=\"unlicensed dependency\" group by project) c\non z.product_name=c.project \ngroup by z.product_name;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Sonar Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "quality_gate_status",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Warning / Critical",
     "queryText": "select project, quality_gate_status from sonar_metrics;",
     "rawQueryText": "select project, quality_gate_status from sonar_metrics;",
     "timeColumns": [
      "time",
      "ts"
     ],
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "Data Update",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "queryText": "select metric , last_run as \"Update Timestamp\" from last_update;",
     "rawQueryText": "select metric , last_run as \"Update Timestamp\" from last_update;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}